- hosts: ubuntu
  become: yes
  tasks: 

    - name: install java1.8
      apt:
        name: openjdk-8-jdk
        state: installed

    - name: install maven
      apt:
        name: maven
        state: present

    - name: install git
      apt:
        name: git
        state: latest

    - name: cloning vprifile
      git:
        repo: https://github.com/kommarer/VProfile.git
        dest: /home/priyatham/project

    - name: getting artifact
      shell: mvn -f /home/priyatham/project package 
        
