- hosts: ubuntu
  become: yes
  tasks: 

    - name: install java1.8
      apt:
        name: openjdk-8-jdk
        state: installed

    - name: install maven
      apt:
        name: maven
        state: present

    - name: install git
      apt:
        name: git
        state: latest

    - name: cloning vprifile
      git:
        repo: https://github.com/kommarer/VProfile.git
        dest: /home/priyatham/project

    - name: getting artifact
      shell: mvn -f /home/priyatham/project package 
        
    - name: download tomcat
      get_url:
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.45/bin/apache-tomcat-8.5.45.tar.gz
        dest: /home/priyatham
        remote_src: yes

    - name: unzip tar file
      unarchive:
         src: /home/priyatham/apache-tomcat-8.5.45.tar.gz 
         dest: /home/priyatham
         remote_src: yes

    - name: copy war file
      copy:
        src: /home/priyatham/project/target/vprofile-v1.war 
        dest: /home/priyatham/apache-tomcat-8.5.45/webapps
        remote_src: yes

    - name: start tomcat
      shell: nohup /home/priyatham/apache-tomcat-8.5.45/bin/startup.sh &  
        
 
